### PR TITLE
Only grey-out case row

### LINKED ISSUE #469: Whole case select/unselect grays out the entire page
When changing the checkbox of individual samples - only the single case row is "grayed out" during the operation.

However, when changing the checkbox of a case - the entire page of cases "grays out" during the operation. Wondering if it is possible to get it to behave the same as the sample checkbox case?

### PR DESCRIPTION
**Pull request by DoxasticFox**
Closes https://github.com/elsa-data/elsa-data/issues/469

### CODE REVIEW

**Comment by andrewpatto** [comment]
So you've dropped the operation one level down in the react component hierarchy?

**Review by andrewpatto — APPROVED** [review]

**Comment by DoxasticFox** [comment]
@andrewpatto Yep. Sounds good?

Demo I should've added to the OP:

https://github.com/elsa-data/elsa-data/assets/11529449/fcb0f9ba-3643-4fd0-885a-daa861a3ae21

**Comment by andrewpatto** [comment]
Yep sounds like a good approach. Looks good.

**Comment by andrewpatto** [comment]
I'm about to make a proper release - so will merge on your behalf now

**Pull request merged**
