### PR TITLE
Role in release

### LINKED ISSUE #156: Return users Role in the release as a field in the API
When returning the list of releases, it would be useful if it was customised to the logged in user to show them what sort of role they have (DataOwner etc).

There was a bug in EdgeDb that meant that the query that would enable that data query was failing - but that was 1.x. Should try again until this works (it should be a relatively straight forward edge query so was surprised it failed)

### PR DESCRIPTION
**Pull request by andrewpatto**
The link property "@role" didn't use to be able to be extracted in our edge queries. It is still a bug with Edge but I've just re-oriented the queries to make it work.

### CODE REVIEW

**Comment by andrewpatto** [comment]
Screenshot 2022-12-12 at 4 22 58 pm

Added "Role (in release)" to the UI

**Comment by andrewpatto** [comment]
Also added a Loader div whilst I was there..

**Comment by andrewpatto** [comment]
btw we have a new prettier extension in "pre-commit" that is normalising tailwind css classes (hence why these have automatically changed in the files I've edited).

What I will do soon is do a PR that is specifically just normalising the entire React (but will wait for all front end PRs to be shut so there is no clashes)

**Comment by andrewpatto** [comment]
We are displaying the raw db "PI", "DataOwner" string in the UI - which is something we can revisit (is easy to map to different language strings)

**Review by williamputraintan — APPROVED** [review]
LGTM

**Comment by andrewpatto** [comment]
closes #156

**Pull request merged**
