### PR TITLE
fix(backend): add transport targets to deploy config

### PR DESCRIPTION
**Pull request by mmalenic**
Adds a transport targets field to the deployed logger config to avoid errors with invalid types

### CODE REVIEW

**Comment by andrewpatto** [comment]
So we need to start thinking about the distinction between configs for dev itself, configs for running locally but in the dev account, and configs for actually deploying an image into dev.
So everything in the config/ folder won't make it through into the actual Docker imag..

**Comment by andrewpatto** [comment]
Configs for actually dev deployment - should live in the assets folder in the aws-deploy project

**Comment by andrewpatto** [comment]
(not saying this PR is wrong - just saying I don't know where we currently are in all of this)

**Comment by mmalenic** [comment]
Yes, you're right. Maybe there shouldn't even be a dev-deployed config in this repository?

**Comment by andrewpatto** [comment]
Yes - I think it pre-dates us even having a deployable AWS stack.

But we do have a use case for _running_ Elsa locally - but with dev AWS credentials - and so I think some of these settings inhabited both worlds?

**Comment by andrewpatto** [comment]
For instance - the pretty printer for debug should *only* be enabled for local dev runs (it puts colours into the console logs).

For cloudwatch the colours will be useless - so we definitely don't want this for AWS actual deployments

**Comment by mmalenic** [comment]
Yes that's true. I guess it can help with calling `file('dev-deployed')` in the meta configs of the aws-deploy repo, so it does sort of serve two purposes. Although, probably any config for deployment should just be in that repo instead.

**Comment by andrewpatto** [comment]
Yes -lets split them - anything in config/ in the Elsa repo should *only* make sense for local dev deployment

Anything needed by the dev deployment should go over into the other aws-deploy repo

**Comment by mmalenic** [comment]
Okay, I think this PR is now correct, as it fixes the default behaviour for the logger config, which was throwing an error before.

**Review by andrewpatto — APPROVED** [review]

**Pull request merged**
