### PR TITLE
Feature/mock access point with sharer tidy

### PR DESCRIPTION
**Pull request by andrewpatto**

### CODE REVIEW

**Comment by andrewpatto** [comment]
Ok this has already got big enough - if it can be reviewed keeping in mind it is still partly WIP.

I mean it now works as a feature - as opposed to previously not working as a feature - so is definitely better than before. But it needs some other refactorings before I'm happy with it.
But need to merge it so others can get on with stuff.

**Comment by andrewpatto** [comment]
The idea here is that this feature now works via mocks as well - so can be run locally with no AWS in dev.

**Comment by andrewpatto** [comment]
Screenshot 2023-06-28 at 4 34 24 pm

**Review by williamputraintan — APPROVED** [review]
LGTM! Agree that we need to split out the sharer box component.

**Review by mmalenic — APPROVED** [review]

**Comment by DoxasticFox** [comment]
This appears to have introduced a minor bug. In my browser's console, when accessing `http://localhost:3000/releases/R006/detail` as a SuperAdmin:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `AwsAccessPointAccordionContent`. See https://reactjs.org/link/warning-keys for more information.
    at option
    at AwsAccessPointAccordionContent (http://localhost:3000/assets/index.6ed1fa03.js:73661:23)
    at div
    at div
    at SharingConfigurationAccordion (http://localhost:3000/assets/index.6ed1fa03.js:73296:28)
    at InputWrapper (http://localhost:3000/assets/index.6ed1fa03.js:73898:3)
    at div
    at fieldset
    at RhChecks (http://localhost:3000/assets/index.6ed1fa03.js:73123:3)
    at div
    at RightDiv (http://localhost:3000/assets/index.6ed1fa03.js:73074:21)
    at div
    at RhSection (http://localhost:3000/assets/index.6ed1fa03.js:73009:21)
    at ErrorFormatter (http://localhost:3000/assets/index.6ed1fa03.js:38397:3)
    at ErrorBoundary (http://localhost:3000/assets/index.6ed1fa03.js:38477:5)
    at div
    at div
    at Box (http://localhost:3000/assets/index.6ed1fa03.js:45065:12)
    at SharerControlBox (http://localhost:3000/assets/index.6ed1fa03.js:73924:3)
    at ReleasesDetailSubPage (http://localhost:3000/assets/index.6ed1fa03.js:74980:7)
    at RenderedRoute (http://localhost:3000/assets/index.6ed1fa03.js:41314:5)
    at Outlet (http://localhost:3000/assets/index.6ed1fa03.js:41546:26)
    at div
    at ReleasesMasterPage (http://localhost:3000/assets/index.6ed1fa03.js:76111:7)
    at RenderedRoute (http://localhost:3000/assets/index.6ed1fa03.js:41314:5)
    at RenderedRoute (http://localhost:3000/assets/index.6ed1fa03.js:41314:5)
    at Outlet (http://localhost:3000/assets/index.6ed1fa03.js:41546:26)
    at ProtectedRoute (http://localhost:3000/assets/index.6ed1fa03.js:85598:5)
    at RenderedRoute (http://localhost:3000/assets/index.6ed1fa03.js:41314:5)
    at Outlet (http://localhost:3000/assets/index.6ed1fa03.js:41546:26)
    at div
    at ErrorFormatter (http://localhost:3000/assets/index.6ed1fa03.js:38397:3)
    at ErrorBoundary (http://localhost:3000/assets/index.6ed1fa03.js:38477:5)
    at div
    at div
    at LayoutBase (http://localhost:3000/assets/index.6ed1fa03.js:75504:3)
    at RenderedRoute (http://localhost:3000/assets/index.6ed1fa03.js:41314:5)
    at RenderErrorBoundary (http://localhost:3000/assets/index.6ed1fa03.js:41268:5)
    at Routes (http://localhost:3000/assets/index.6ed1fa03.js:41615:5)
    at Router (http://localhost:3000/assets/index.6ed1fa03.js:41553:15)
    at RouterProvider (http://localhost:3000/assets/index.6ed1fa03.js:41457:5)
    at IndexRouter (http://localhost:3000/assets/index.6ed1fa03.js:85555:13)
    at LoggedInUserConfigRelayProvider (http://localhost:3000/assets/index.6ed1fa03.js:57538:24)
    at QueryClientProvider (http://localhost:3000/assets/index.6ed1fa03.js:44838:3)
    at TRPCProvider2 (http://localhost:3000/assets/index.6ed1fa03.js:46471:7)
    at TRPCProvider (http://localhost:3000/assets/index.6ed1fa03.js:85912:48)
    at LoggedInUserProvider (http://localhost:3000/assets/index.6ed1fa03.js:37424:48)
    at ShowAlert (http://localhost:3000/assets/index.6ed1fa03.js:37371:51)
    at CookiesProvider2 (http://localhost:3000/assets/index.6ed1fa03.js:24065:24)
    at EnvRelayProvider (http://localhost:3000/assets/index.6ed1fa03.js:23797:21)
    at ErrorFormatter (http://localhost:3000/assets/index.6ed1fa03.js:38397:3)
    at ErrorBoundary (http://localhost:3000/assets/index.6ed1fa03.js:38477:5)
    ```

**Comment by andrewpatto** [comment]
Cheers! I will fix.. thanks

**Pull request merged**
