### PR TITLE
Modernise the docker publish with some newer actions

### PR DESCRIPTION
**Pull request by andrewpatto**
Use git token credentials rather than personal ones

### CODE REVIEW

**Comment by andrewpatto** [comment]
Doing some loops here to trigger docker builds

**Comment by andrewpatto** [comment]
Make the docker build params mandatory so we don't ever forget them

**Comment by andrewpatto** [comment]
Use some new actions from Docker that help create tags based off github refs

**Comment by andrewpatto** [comment]
Increase how often we publish - pretty much every commit goes to images tagged with PR name
(may have to dial back but will monitor)

**Comment by andrewpatto** [comment]
I won't be able to test the 'release' build process until this is merged - so we may need another round of changes if that doesn't work

**Review by DoxasticFox — APPROVED** [review]

**Pull request merged**
